#### _ML продвинутые методы / ДЗ №1 / Теоретическая часть_

In [1]:
import numpy as np

## _Задача №1_ 

In [2]:
X = 1 + np.arange(7)

X

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
Y = np.array([100, 102, 103, 50, 55, 61, 70])
             
Y

array([100, 102, 103,  50,  55,  61,  70])

In [4]:
np.var(Y)

478.2040816326531

Будем определять правила разбиения, находя максимум информационного прироста.

In [5]:
def Q(hrf, X, Y):
    HR = hrf(Y)
    for i, x in enumerate(X):
        if 0 == i:
            continue
        l = X < x
        r = ~l
        HRl = hrf(Y[l])
        HRr = hrf(Y[r])
        Q = HR - ((len(np.argwhere(l)) / len(X)) * HRl) - ((len(np.argwhere(r)) / len(X)) * HRr)
        print('[{}] [ x < {} ] [{} / {}] HR(l): {:.3f}, HR(r): {:.3f}, Q: {:.3f}'.format(i, x, X[l], X[r], HRl, HRr, Q))

In [6]:
Q(np.var, X, Y)

[1] [ x < 2 ] [[1] / [2 3 4 5 6 7]] HR(l): 0.000, HR(r): 457.583, Q: 85.990
[2] [ x < 3 ] [[1 2] / [3 4 5 6 7]] HR(l): 1.000, HR(r): 354.160, Q: 224.947
[3] [ x < 4 ] [[1 2 3] / [4 5 6 7]] HR(l): 1.556, HR(r): 55.500, Q: 445.823
[4] [ x < 5 ] [[1 2 3 4] / [5 6 7]] HR(l): 501.688, HR(r): 38.000, Q: 175.240
[5] [ x < 6 ] [[1 2 3 4 5] / [6 7]] HR(l): 583.600, HR(r): 20.250, Q: 55.561
[6] [ x < 7 ] [[1 2 3 4 5 6] / [7]] HR(l): 547.583, HR(r): 0.000, Q: 8.847


In [7]:
Q(np.var, X[X<4], Y[X<4])

[1] [ x < 2 ] [[1] / [2 3]] HR(l): 0.000, HR(r): 0.250, Q: 1.389
[2] [ x < 3 ] [[1 2] / [3]] HR(l): 1.000, HR(r): 0.000, Q: 0.889


In [8]:
Q(np.var, X[X>=4], Y[X>=4])

[1] [ x < 5 ] [[4] / [5 6 7]] HR(l): 0.000, HR(r): 38.000, Q: 27.000
[2] [ x < 6 ] [[4 5] / [6 7]] HR(l): 6.250, HR(r): 20.250, Q: 42.250
[3] [ x < 7 ] [[4 5 6] / [7]] HR(l): 20.222, HR(r): 0.000, Q: 40.333


Получили следующее дерево:
```
                        { x < 4 }[#7]
                           True | False
               +----------------+----------------+
               |                                 |
       { x < 2 }[#3]                     { x < 6 }[#4]
          True | False                      True | False
      +--------+--------+               +--------+--------+
      |                 |               |                 |
    {1}[#1]         {2,3}[#2]       {4,5}[#2]         {6,7}[#2]

```

## _Задача №2_ 

In [9]:
def gini(X):
    unique, counts = np.unique(X, return_counts=True)
    probs = counts / X.shape[0]
    return np.sum(probs * (1. - probs))

Индекс Джини будет больше `0.9999`, например, если у нас будет выборка из более чем `10000` элементов, каждый из которых принадлежит к своему уникальному классу (ну или просто одинаковое число элеметнов каждого класса при общем объёме выборки более `10000`).

In [10]:
X = 1 + np.arange(10000)

X

array([    1,     2,     3, ...,  9998,  9999, 10000])

In [11]:
gini(X)

0.9999000000000005

## _Задача №3_ 

In [12]:
X = np.array([10, 11, 12, 13, 14])

X

array([10, 11, 12, 13, 14])

In [13]:
Y = np.array(['плюнет', 'поцелует', 'поцелует', 'к сердцу прижмёт', 'к сердцу прижмёт'])

Y

array(['плюнет', 'поцелует', 'поцелует', 'к сердцу прижмёт',
       'к сердцу прижмёт'], dtype='<U16')

In [14]:
Q(gini, X, Y)

[1] [ x < 11 ] [[10] / [11 12 13 14]] HR(l): 0.000, HR(r): 0.500, Q: 0.240
[2] [ x < 12 ] [[10 11] / [12 13 14]] HR(l): 0.500, HR(r): 0.444, Q: 0.173
[3] [ x < 13 ] [[10 11 12] / [13 14]] HR(l): 0.444, HR(r): 0.000, Q: 0.373
[4] [ x < 14 ] [[10 11 12 13] / [14]] HR(l): 0.625, HR(r): 0.000, Q: 0.140


In [15]:
Q(gini, X[X<13], Y[X<13])

[1] [ x < 11 ] [[10] / [11 12]] HR(l): 0.000, HR(r): 0.000, Q: 0.444
[2] [ x < 12 ] [[10 11] / [12]] HR(l): 0.500, HR(r): 0.000, Q: 0.111


Получили следующее дерево:
```
                          { x < 13 }[#5]
                              True | False
                  +----------------+----------------+
                  |                                 |
         { x < 11 }[#3]          {'к сердцу прижмёт'}[#2]
             True | False
         +--------+--------+
         |                 |
{'плюнет'}[#1]  {'поцелует'}[#2]

```