## NN and deep learning #2
### Basic NN implementation

In [14]:
import numpy as np

In [30]:
def sigmoid(t): return 1 / (1 + np.exp(-t))
def sigmoid_derivative(p): return p * (1 - p)

In [31]:
def loss(y, y_out):
    return np.mean(np.square(y-y_out))

In [79]:
class NeuralNetwork:
    def __init__(self, x, y, learning_rate=1.):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1], 4)
        self.weights2 = np.random.rand(4, 1)
        self.y = y
        self.output = np.zeros(self.y.shape)
        self.learning_rate = learning_rate
    
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        return self.output

    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) *
                                            sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T, (np.dot(2*(self.y - self.output) *
                                                  sigmoid_derivative(self.output), self.weights2.T)
                                           * sigmoid_derivative(self.layer1)))
        
        self.weights2 += self.learning_rate * d_weights2
        self.weights1 += self.learning_rate * d_weights1
    
    def train(self):
        self.output = self.feedforward()
        self.backprop()

In [80]:
def print_results(i, X, y, y_out):
    print('Epoch #: {}'.format(i))
    print('Actual y: {}'.format(y))
    print('Predict y: {}'.format(y_out))
    print('Loss function: {:.4f}'.format(loss(y, y_out)))
    print("*"*40)

In [81]:
X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]], dtype=float)

X

array([[0., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [82]:
y = np.array([0, 1, 1, 0]).reshape(-1, 1)

y

array([[0],
       [1],
       [1],
       [0]])

In [88]:
n_epoch = 10000

ANN = NeuralNetwork(X, y, learning_rate=0.1)

for i in range(0, n_epoch):
    ANN.train()
    if 0 == (i + 1) % 1000:
        y_out = ANN.output
        print_results(i + 1, X, y.squeeze(), y_out.squeeze())

Epoch #: 1000
Actual y: [0 1 1 0]
Predict y: [0.41644989 0.51591688 0.5535174  0.54781764]
Loss function: 0.2268
****************************************
Epoch #: 2000
Actual y: [0 1 1 0]
Predict y: [0.11583583 0.75267337 0.76660482 0.30311411]
Loss function: 0.0552
****************************************
Epoch #: 3000
Actual y: [0 1 1 0]
Predict y: [0.04976894 0.88662009 0.88907167 0.13273499]
Loss function: 0.0113
****************************************
Epoch #: 4000
Actual y: [0 1 1 0]
Predict y: [0.03300878 0.92289936 0.92441166 0.08886073]
Loss function: 0.0052
****************************************
Epoch #: 5000
Actual y: [0 1 1 0]
Predict y: [0.02552884 0.93966898 0.94082414 0.06896498]
Loss function: 0.0031
****************************************
Epoch #: 6000
Actual y: [0 1 1 0]
Predict y: [0.02122641 0.94949102 0.95044881 0.05743398]
Loss function: 0.0022
****************************************
Epoch #: 7000
Actual y: [0 1 1 0]
Predict y: [0.01839651 0.95602385 0.956853

In [85]:
ANN.weights1

array([[ 4.24976414, -1.11735376,  4.49689319,  6.00484415],
       [-1.70296912,  5.43019136, -1.93351641,  5.73833311],
       [ 0.09567294, -1.28306374,  0.21458986, -1.61839874]])

In [86]:
ANN.weights2

array([[-3.2286471 ],
       [-6.01941195],
       [-3.48390307],
       [ 9.71290212]])