# NumPy 

NumPy - это библиотека языка Python для работы с линейной алгеброй. Это быстрый способ работы с данными, так как эта библиотека написана на языке C. И, например, предпочтительно использовать массивы Numpy вместо питоновских листов, так как это будет быстрее и эффективнее. 

## Использование NumPy

In [1]:
import numpy as np

## Создание NumPy Arrays

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
# Создание n-мерных матриц
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Встроенные методы

In [6]:
# Списки
np.arange(5, 15, 3), np.arange(1, 20)

(array([ 5,  8, 11, 14]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19]))

In [7]:
# Нули
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# Единицы
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
# Равномерно распределенное заданное кол-во чисел в интервале
np.linspace(10,20,15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

In [12]:
# Единичная матрица
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# Случайные равномерно распределенные числа в диапазоне [0; 1)
np.random.rand(5)

array([0.90076307, 0.11386098, 0.48146272, 0.77812832, 0.57410106])

In [14]:
np.random.rand(5, 3)

array([[0.25161718, 0.83851329, 0.09219767],
       [0.86082685, 0.72862183, 0.31493517],
       [0.45612215, 0.7422485 , 0.96766418],
       [0.51950014, 0.84051228, 0.82207809],
       [0.74490925, 0.8666751 , 0.91954412]])

In [15]:
# Случайные нормально распределенные числа
np.random.randn(5)

array([ 1.60539105, -1.27862487,  1.80242471, -0.78154246, -0.25865627])

In [16]:
np.random.randn(3, 5)

array([[-0.37270708, -0.55674793,  1.54316635, -0.12735403, -1.89279132],
       [-0.75113121,  0.46174318, -0.02188428, -0.38858685, -0.91430134],
       [ 0.36534302,  1.29429429, -0.24868884,  1.06758273, -0.48095709]])

In [17]:
# Случайные равномерно распределенные целые числа в диапазоне [min; max)
np.random.randint(10, 20)

14

In [18]:
np.random.randint(10, 20, 15)

array([17, 16, 17, 14, 17, 10, 15, 15, 19, 12, 12, 18, 17, 16, 15])

## Методы

In [19]:
ar = np.arange(42)
arran = np.random.randint(10, 20, 15) 

In [20]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [21]:
arran

array([14, 12, 14, 13, 18, 11, 16, 14, 19, 17, 11, 12, 17, 18, 17])

In [22]:
# Преобразование в другую размерность
ar.reshape(7, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [23]:
# Поиск максимума массива
arran.max()

19

In [24]:
# Поиск положения максимума массива
arran.argmax()

8

In [25]:
# Поиск минимума массива
arran.min()

11

In [26]:
# Поиск положения минимума массива
arran.argmin()

5

In [27]:
# Вектор
ar.shape

(42,)

In [28]:
# Массив
ar.reshape(1, 42)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41]])

In [29]:
# Изменение размерности
ar.reshape(1, 42).shape

(1, 42)

In [30]:
ar.reshape(21, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41]])

In [31]:
ar.reshape(21, 2).shape

(21, 2)

In [32]:
# Тип данных
ar.dtype

dtype('int64')

In [33]:
# Фильтрация 
ar[ar<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Индексирование и выбор части

In [34]:
# Счет позиции начинается с 0
# Одно число на 5 месте
ar[5]

5

In [35]:
# Первые 5 чисел
ar[:5]

array([0, 1, 2, 3, 4])

In [36]:
# Присвоение части чисел другого значения
ar[5:10] = 42
ar

array([ 0,  1,  2,  3,  4, 42, 42, 42, 42, 42, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [37]:
# Выбор части данных, в этом случае 5 последних
slice_ar = ar[-5:]
slice_ar

array([37, 38, 39, 40, 41])

In [38]:
# Копирование массива
ar_copy = ar.copy()
ar_copy

array([ 0,  1,  2,  3,  4, 42, 42, 42, 42, 42, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [39]:
# Создание матрицы
data = np.array(([3, 6, 9], [10, 15, 30], [42, 88, 333]))
data

array([[  3,   6,   9],
       [ 10,  15,  30],
       [ 42,  88, 333]])

In [40]:
# Выбор строки
data[2]

array([ 42,  88, 333])

In [41]:
# Выбор числа в матрице
data[2][0]

42

In [42]:
data[:2,1:]

array([[ 6,  9],
       [15, 30]])

In [43]:
data[[2, 0]]

array([[ 42,  88, 333],
       [  3,   6,   9]])

## Операции

In [44]:
ar + ar

array([ 0,  2,  4,  6,  8, 84, 84, 84, 84, 84, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82])

In [45]:
1/ar

/Users/yellowduck/miniconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.02380952, 0.02380952, 0.02380952, 0.02380952, 0.02380952,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667,
       0.04      , 0.03846154, 0.03703704, 0.03571429, 0.03448276,
       0.03333333, 0.03225806, 0.03125   , 0.03030303, 0.02941176,
       0.02857143, 0.02777778, 0.02702703, 0.02631579, 0.02564103,
       0.025     , 0.02439024])

In [46]:
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       6.4807407 , 6.4807407 , 6.4807407 , 6.4807407 , 6.4807407 ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424])

In [47]:
# np.exp(), np.max(), np.sin(), np.log()

In [48]:
np.log(ar)

/Users/yellowduck/miniconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       3.73766962, 3.73766962, 3.73766962, 3.73766962, 3.73766962,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207])

## Блиц
##### 1. Что больше, $\pi^e$ или $e^\pi$? Выведете результат $\pi^e > e^\pi$ 

Воспользуйтесь встроенными константами np.pi и np.e

##### 2. Фильтрация элементов в массиве

(1 балл) Создайте массив из последовательности чисел от 1 до 10 (функция <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html">np.arange</a>)

(1 балл) Выведите этот массив в обратном порядке. 

(1 балл) Выведите каждый второй элемент. 

(1 балл) Выведите элементы, большие числа 3. (<a href="https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html">numpy indexing tutorial</a>)

##### 3.  Операции с массивами

(1 балл) Создайте 5 одномерных массивов длины 7: первый из единиц, второй из двоек и т.д.

(1 балл) Объедините массивы с помощью функции <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html">np.vstack</a> в матрицу A (на самом деле 2-мерный массив).

(1 балл) Сделайте копию А с помощью <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.copy.html">np.copy</a> и назовите её B.

(1 балл) Вычислите <a href="https://ru.wikipedia.org/wiki/Умножение_матриц">матричное произведение</a> (оператор @) между матрицей A и B транспонированной (метод <a href="https://docs.scipy.org/doc/numpy-1.9.1/reference/generated/numpy.ndarray.T.html">.T</a>).

Выведите ответ.

##### 4. Max / min

Найдите максимум и минимум массива A (методы <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.max.html">.max</a> и <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.min.html">.min</a> класса numpy.ndarray). Так же найдите максимумы в строках и столбцах (параметр axis).

##### 5. Индексирование*
Напишите функцию, возвращающую максимальный элемент в векторе `x` среди элементов, перед которыми стоит число 0. <br>
Для `x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])` ответом является `5`. Если нулевых элементов нет, функция должна возвращать None.

Для решения можно использовать функцию <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html">np.where</a>. Эта функция может быть использована для получения индексов элементов в массиве, которые подчиняются логическому условию. Например:
`np.where(np.array([1, 4, 7, 5, 2]) % 2 == 0)[0]` возвращает индексы четных элементов: `array([1, 4])`

# Pandas

## Series

Начнем изучение pandas с рядов. Ряды очень похожи на NumPy array. Различие в том, что ряды могут иметь не только числовые индексы, а состоящие из любых Python объектов.

Разберем некоторые примеры.

In [49]:
import numpy as np
import pandas as pd

### Создание

В ряд можно превратить лист, numpy array, или словарь:

In [50]:
spells = ['Accio','Riddikulus','Expelliarmus']
power = [100, 300, 500]
arr = np.array([100, 300, 500])
dict_of_spells = {'Accio':100, 'Riddikulus':200, 'Expelliarmus':300}

**Лист**

In [51]:
pd.Series(power)

0    100
1    300
2    500
dtype: int64

In [52]:
pd.Series(data=power, index=spells)

Accio           100
Riddikulus      300
Expelliarmus    500
dtype: int64

**NumPy Arrays**

In [53]:
pd.Series(arr)

0    100
1    300
2    500
dtype: int64

In [54]:
pd.Series(arr, spells)

Accio           100
Riddikulus      300
Expelliarmus    500
dtype: int64

**Словарь**

In [55]:
d_o_s = pd.Series(dict_of_spells)
d_o_s

Accio           100
Expelliarmus    300
Riddikulus      200
dtype: int64

## Использование индекса:

In [56]:
d_o_s['Riddikulus']

200

## DataFrames

DataFrames - это очень удобный инструмент для работы с данными. DataFrames можно представлять как набор индексированных одним индексом рядов.

In [129]:
from numpy.random import randint

In [130]:
# Создание DataFrame
np.random.seed(42)
df = pd.DataFrame(randint(50, 100, size=(4,8)),index='Harry Ron Luna Neville'.split(),
                  columns='Astronomy Charms Flying Herbology History_of_Magic Potions Transfiguration Apparition'.split())

In [131]:
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  
Harry                 88          68  
Ron                   73          52  
Luna                  51          70  
Neville               76          91

## Выбор и индексация

In [132]:
df['Potions']

Harry      70
Ron        89
Luna       87
Neville    98
Name: Potions, dtype: int64

In [133]:
# Выбор нескольких колонок по именам колонок
df[['History_of_Magic', 'Potions']]

History_of_Magic  Potions
Harry                  57       70
Ron                    85       89
Luna                   79       87
Neville                74       98

**Создание новой колонки разными способами:**

In [134]:
# MeanACF = Mean Astronomy Charms Flying - подсчет средней разными способами
df['MeanACF_0'] = (df['Astronomy'] + df['Charms'] + df['Flying']) / 3
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  MeanACF_0  
Harry                 88          68  76.666667  
Ron                   73          52  64.000000  
Luna                  51          70  65.000000  
Neville               76          91  71.333333

In [135]:
df['MeanACF_1'] = df[['Astronomy', 'Charms', 'Flying']].mean(axis=1)
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  MeanACF_0  MeanACF_1  
Harry                 88          68  76.666667  76.666667  
Ron                   73          52  64.000000  64.000000  
Luna                  51          70  65.000000  65.000000  
Neville               76          91  71.333333  71.333333

In [136]:
df['MeanACF_2'] = df[['Astronomy', 'Charms', 'Flying']].apply(lambda x: np.mean(x), axis=1)
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  MeanACF_0  MeanACF_1  MeanACF_2  
Harry                 88          68  76.666667  76.666667  76.666667  
Ron                   73          52  64.000000  64.000000  64.000000  
Luna                  51          70  65.000000  65.000000  65.000000  
Neville               76          91  71.333333  71.333333  71.333333

In [139]:
# Удобство исаользования lambda выражений, через них можно реализовывать широкий перечень несложных функций
df['Apparition_new'] = df['Apparition'].apply(lambda x: x*1.2)
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  MeanACF_0  MeanACF_1  MeanACF_2  \
Harry                 88          68  76.666667  76.666667  76.666667   
Ron                   73          52  64.000000  64.000000  64.000000   
Luna                  51          70  65.000000  65.000000  65.000000   
Neville               76          91  71.333333  71.333333  71.333333   

         Apparition_new  
Harry              81.6  
Ron                62.4  
Luna               84.0  
Neville           109.2

**Удаление колонок**

In [140]:
df.drop('MeanACF_2', axis=1)

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  MeanACF_0  MeanACF_1  Apparition_new  
Harry                 88          68  76.666667  76.666667            81.6  
Ron                   73          52  64.000000  64.000000            62.4  
Luna                  51          70  65.000000  65.000000            84.0  
Neville               76          91  71.333333  71.333333           109.2

In [141]:
# В примере выше реального удаления не произошло, надо добавить inplace
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  MeanACF_0  MeanACF_1  MeanACF_2  \
Harry                 88          68  76.666667  76.666667  76.666667   
Ron                   73          52  64.000000  64.000000  64.000000   
Luna                  51          70  65.000000  65.000000  65.000000   
Neville               76          91  71.333333  71.333333  71.333333   

         Apparition_new  
Harry              81.6  
Ron                62.4  
Luna               84.0  
Neville           109.2

In [142]:
df.drop(['MeanACF_0', 'MeanACF_1', 'MeanACF_2', 'Apparition_new'], axis=1, inplace=True)

In [143]:
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  
Harry                 88          68  
Ron                   73          52  
Luna                  51          70  
Neville               76          91

Точно так же можно удалять и строки:

In [70]:
df.drop('Luna',axis=0)

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  
Harry                 88          68  
Ron                   73          52  
Neville               76          91

**Индексация по строкам и столбцам**

In [71]:
df.loc['Neville','Astronomy']

82

In [72]:
df.iloc[[1, 0], [4, 5]]

History_of_Magic  Potions
Ron                  85       89
Harry                57       70

In [73]:
df.loc[['Ron','Harry'],['History_of_Magic', 'Potions']]

History_of_Magic  Potions
Ron                  85       89
Harry                57       70

### Выбор по условиям, фильтрация

In [144]:
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  
Harry                 88          68  
Ron                   73          52  
Luna                  51          70  
Neville               76          91

In [145]:
df>80

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry         True   False   False       True             False    False   
Ron          False   False   False      False              True     True   
Luna         False   False   False       True             False     True   
Neville       True   False   False       True             False     True   

         Transfiguration  Apparition  
Harry               True       False  
Ron                False       False  
Luna               False       False  
Neville            False        True

In [146]:
df[df>80]

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry         88.0     NaN     NaN       92.0               NaN      NaN   
Ron            NaN     NaN     NaN        NaN              85.0     89.0   
Luna           NaN     NaN     NaN       93.0               NaN     87.0   
Neville       82.0     NaN     NaN       93.0               NaN     98.0   

         Transfiguration  Apparition  
Harry               88.0         NaN  
Ron                  NaN         NaN  
Luna                 NaN         NaN  
Neville              NaN        91.0

In [77]:
# Фильтрация с помощью условий
df[df['Herbology']>80]

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  
Harry                 88          68  
Luna                  51          70  
Neville               76          91

In [78]:
# Без inplace опять ничего не проиходит с таблицей
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition  
Harry                 88          68  
Ron                   73          52  
Luna                  51          70  
Neville               76          91

Для нескольких условий можно использовать или | и и &:

In [79]:
df[(df['Herbology']>=90) & (df['Transfiguration']>75)][['Flying','Apparition']]

Flying  Apparition
Harry        64          68
Neville      71          91

## Больше информации про индексы

In [151]:
# Удаление индекса до базового 0,1...n index
df.reset_index()

index  Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
0    Harry         88      78      64         92                57       70   
1      Ron         72      60      60         73                85       89   
2     Luna         71      51      73         93                79       87   
3  Neville         82      61      71         93                74       98   

   Transfiguration  Apparition     Surname  
0               88          68      Potter  
1               73          52     Weasley  
2               51          70    Lovegood  
3               76          91  Longbottom

In [148]:
newind = 'Potter Weasley Lovegood Longbottom'.split()

In [149]:
df['Surname'] = newind

In [150]:
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition     Surname  
Harry                 88          68      Potter  
Ron                   73          52     Weasley  
Luna                  51          70    Lovegood  
Neville               76          91  Longbottom

In [84]:
df.set_index('Surname')

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Surname                                                                       
Potter             88      78      64         92                57       70   
Weasley            72      60      60         73                85       89   
Lovegood           71      51      73         93                79       87   
Longbottom         82      61      71         93                74       98   

            Transfiguration  Apparition  
Surname                                  
Potter                   88          68  
Weasley                  73          52  
Lovegood                 51          70  
Longbottom               76          91

In [85]:
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Harry           88      78      64         92                57       70   
Ron             72      60      60         73                85       89   
Luna            71      51      73         93                79       87   
Neville         82      61      71         93                74       98   

         Transfiguration  Apparition     Surname  
Harry                 88          68      Potter  
Ron                   73          52     Weasley  
Luna                  51          70    Lovegood  
Neville               76          91  Longbottom

In [86]:
df.set_index('Surname', inplace=True)

In [87]:
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Surname                                                                       
Potter             88      78      64         92                57       70   
Weasley            72      60      60         73                85       89   
Lovegood           71      51      73         93                79       87   
Longbottom         82      61      71         93                74       98   

            Transfiguration  Apparition  
Surname                                  
Potter                   88          68  
Weasley                  73          52  
Lovegood                 51          70  
Longbottom               76          91

# Другие операции

In [88]:
# Поиск уникальных значений в столбце
df['Herbology'].unique()

array([92, 73, 93])

In [89]:
# Кол-во уникальных значений в столбце
df['Herbology'].nunique()

3

In [90]:
# Сортировка по значениям одного из столбцов
df.sort_values(by='Transfiguration', ascending=False)

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Surname                                                                       
Potter             88      78      64         92                57       70   
Longbottom         82      61      71         93                74       98   
Weasley            72      60      60         73                85       89   
Lovegood           71      51      73         93                79       87   

            Transfiguration  Apparition  
Surname                                  
Potter                   88          68  
Longbottom               76          91  
Weasley                  73          52  
Lovegood                 51          70

In [91]:
# Перечисление всех названий колонок
list(df.columns)

['Astronomy',
 'Charms',
 'Flying',
 'Herbology',
 'History_of_Magic',
 'Potions',
 'Transfiguration',
 'Apparition']

# Пропущенные данные

In [92]:
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Surname                                                                       
Potter             88      78      64         92                57       70   
Weasley            72      60      60         73                85       89   
Lovegood           71      51      73         93                79       87   
Longbottom         82      61      71         93                74       98   

            Transfiguration  Apparition  
Surname                                  
Potter                   88          68  
Weasley                  73          52  
Lovegood                 51          70  
Longbottom               76          91

In [93]:
df = df[df>70]

In [94]:
df

Astronomy  Charms  Flying  Herbology  History_of_Magic  Potions  \
Surname                                                                       
Potter             88    78.0     NaN         92               NaN      NaN   
Weasley            72     NaN     NaN         73              85.0     89.0   
Lovegood           71     NaN    73.0         93              79.0     87.0   
Longbottom         82     NaN    71.0         93              74.0     98.0   

            Transfiguration  Apparition  
Surname                                  
Potter                 88.0         NaN  
Weasley                73.0         NaN  
Lovegood                NaN         NaN  
Longbottom             76.0        91.0

In [95]:
# Кол-во пропусков в каждом столбце
df.isnull().sum()

Astronomy           0
Charms              3
Flying              2
Herbology           0
History_of_Magic    1
Potions             1
Transfiguration     1
Apparition          3
dtype: int64

In [96]:
# Удаление строк с пропусками, по дефолту удаляются те, где хотя бы один пропуск
df.dropna()

Empty DataFrame
Columns: [Astronomy, Charms, Flying, Herbology, History_of_Magic, Potions, Transfiguration, Apparition]
Index: []

In [97]:
# То же самое со столбцами
df.dropna(axis=1)

Astronomy  Herbology
Surname                         
Potter             88         92
Weasley            72         73
Lovegood           71         93
Longbottom         82         93

In [98]:
# Заполнение пропусков
df.fillna(value='-999')

Astronomy Charms Flying  Herbology History_of_Magic Potions  \
Surname                                                                   
Potter             88     78   -999         92             -999    -999   
Weasley            72   -999   -999         73               85      89   
Lovegood           71   -999     73         93               79      87   
Longbottom         82   -999     71         93               74      98   

           Transfiguration Apparition  
Surname                                
Potter                  88       -999  
Weasley                 73       -999  
Lovegood              -999       -999  
Longbottom              76         91

# Группировка

Группировки в pandas - это очень мощный инструмент, здесь приведено лишь несколько примеров. Но в интеренете можно найти много туториалов по работе с groupby для решения ваших конкретных задач.

Вводая по данным:
Департамент регулирования и контроля магических существ классифицирует всех магических существ по шкале от 1 (X) до 5 (XXXXX) таким образом:

XXXXX: Known wizard killer / impossible to train or domesticate

XXXX: Dangerous / requires specialist knowledge / skilled wizard may handle

XXX: Competent wizards should cope

XX: Harmless / may be domesticated

X: Boring

In [99]:
np.random.seed(4242)

X = ['Flobberworm', 'Horklump']
XX = ['Augurey', 'Bowtruckle', 'Chizpurfle', 'Clabbert', 'Diricawl', 'Fairy', 'Ghoul', 
      'Gnome', 'Grindylow', 'Imp', 'Jobberknoll', 'Mooncalf', 'Porlock', 'Puffskein', 'Ramora', 'Winged horse']
XXX = ['Ashwinder', 'Billywig', 'Bundimun', 'Crup', 'Doxy', 'Dugbog', 'Fire crab', 
       'Fwooper', 'Glumbumble', 'Hippocampus', 'Hippogriff', 'Hodag', 'Jarvey', 'Knarl', 'Kneazle', 
       'Leprechaun', 'Lobalug', 'Mackled Malaclaw', 'Moke', 'Murtlap', 'Niffler', 'Nogtail', 'Pixie',
       'Plimpy', 'Pogrebin', 'Red Cap', 'Salamander', 'Sea serpent', 'Shrake', 'Streeler', 'Winged horse']
XXXX = ['Centaur', 'Demiguise', 'Erkling', 'Erumpent', 'Golden Snidget', 'Graphorn', 'Griffin', 'Hidebehind',
        'Kappa', 'Kelpie', 'Merpeople', 'Occamy', 'Phoenix', "Re'em", 'Runespoor', 'Snallygaster', 'Sphinx',
        'Tebo', 'Thestral', 'Thunderbird', 'Troll', 'Unicorn', 'Winged horse', 'Yeti']
XXXXX = ['Acromantula', 'Basilisk', 'Chimaera', 'Dragon', 'Horned Serpent', 'Lethifold', 'Manticore',
         'Nundu', 'Quintaped', 'Wampus cat', 'Werewolf']

X_count = len(X)
XX_count = len(XX)
XXX_count = len(XXX)
XXXX_count = len(XXXX)
XXXXX_count = len(XXXXX)

Class = ['X']*X_count + ['XX']*XX_count + ['XXX']*XXX_count + ['XXXX']*XXXX_count + ['XXXXX']*XXXXX_count
Creatures = X + XX + XXX + XXXX + XXXXX

data = {'Class': Class,
        'Creature': Creatures,
        'Prettiness': randint(0, 100, size = (len(Class)))}


In [100]:
data = pd.DataFrame(data)
data.head()

Class     Creature  Prettiness
0     X  Flobberworm          46
1     X     Horklump          13
2    XX      Augurey          17
3    XX   Bowtruckle          54
4    XX   Chizpurfle          34

In [101]:
# Сгруппируем данные по классам и посмотрим на среднюю оценку симпатичности
data.groupby('Class')['Prettiness'].mean()

Class
X        29.500000
XX       47.500000
XXX      47.548387
XXXX     63.416667
XXXXX    46.545455
Name: Prettiness, dtype: float64

In [102]:
# Это можно сделать и иным способом. В agg() можно передавать любые функции
data.groupby('Class')['Prettiness'].agg(np.mean)

Class
X        29.500000
XX       47.500000
XXX      47.548387
XXXX     63.416667
XXXXX    46.545455
Name: Prettiness, dtype: float64

In [103]:
# Подсчет кол-ва элементов в группах
data.groupby('Class')['Prettiness'].count()

Class
X         2
XX       16
XXX      31
XXXX     24
XXXXX    11
Name: Prettiness, dtype: int64

In [104]:
# проверка пролого вывода, все сходится.
data['Class'].value_counts()

XXX      31
XXXX     24
XX       16
XXXXX    11
X         2
Name: Class, dtype: int64

In [105]:
# Вывод макимального значения в группе
by_class = data.groupby('Class')
by_class.max()

Creature  Prettiness
Class                          
X          Horklump          46
XX     Winged horse          93
XXX    Winged horse          98
XXXX           Yeti          99
XXXXX      Werewolf          87

In [106]:
# Описание групп
by_class.describe()

Prettiness                                                      
           count       mean        std   min    25%   50%    75%   max
Class                                                                 
X            2.0  29.500000  23.334524  13.0  21.25  29.5  37.75  46.0
XX          16.0  47.500000  26.715788  13.0  28.75  41.0  67.50  93.0
XXX         31.0  47.548387  29.323300   0.0  22.50  48.0  64.50  98.0
XXXX        24.0  63.416667  27.347866   3.0  49.00  70.5  84.00  99.0
XXXXX       11.0  46.545455  19.438949  13.0  36.00  44.0  55.50  87.0

# Объединение таблиц

Существует несколько основных способов объединения DataFrames вместе.

In [107]:
# Обратите внимание на индекс в этом примере, он не пересекается.
df1 = pd.DataFrame({'Gryffindor': ['G0', 'G1', 'G2', 'G3'],
                        'Hufflepuff': ['H0', 'H1', 'H2', 'H3'],
                        'Ravenclaw': ['R0', 'R1', 'R2', 'R3'],
                        'Slytherin': ['S0', 'S1', 'S2', 'S3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'Gryffindor': ['G4', 'G5', 'G6', 'G7'],
                        'Hufflepuff': ['H4', 'H5', 'H6', 'H7'],
                        'Ravenclaw': ['R4', 'R5', 'R6', 'R7'],
                        'Slytherin': ['S4', 'S5', 'S6', 'S7']},
                        index=[4, 5, 6, 7])

df3 = pd.DataFrame({'Gryffindor': ['G8', 'G9', 'G10', 'G11'],
                        'Hufflepuff': ['H8', 'H9', 'H10', 'H11'],
                        'Ravenclaw': ['R8', 'R9', 'R10', 'R11'],
                        'Slytherin': ['S8', 'S9', 'S10', 'S11']},
                        index=[8, 9, 10, 11])

In [108]:
df1

Gryffindor Hufflepuff Ravenclaw Slytherin
0         G0         H0        R0        S0
1         G1         H1        R1        S1
2         G2         H2        R2        S2
3         G3         H3        R3        S3

In [109]:
df2

Gryffindor Hufflepuff Ravenclaw Slytherin
4         G4         H4        R4        S4
5         G5         H5        R5        S5
6         G6         H6        R6        S6
7         G7         H7        R7        S7

## Concatenation

Concatenation склеивает DataFrames вместе. Помните, что размерность данных по той оси, по которой склеиваете, должна совпадать у всех склеиваемых частей, если только не вмешивается индекс. **pd.concat** можно просто передать лист таблиц, которые будут объединены:

In [110]:
pd.concat([df1,df2,df3])

Gryffindor Hufflepuff Ravenclaw Slytherin
0          G0         H0        R0        S0
1          G1         H1        R1        S1
2          G2         H2        R2        S2
3          G3         H3        R3        S3
4          G4         H4        R4        S4
5          G5         H5        R5        S5
6          G6         H6        R6        S6
7          G7         H7        R7        S7
8          G8         H8        R8        S8
9          G9         H9        R9        S9
10        G10        H10       R10       S10
11        G11        H11       R11       S11

In [111]:
# Сравните этот случай, с непересекающимся индексом
pd.concat([df1,df2,df3], axis=1)

Gryffindor Hufflepuff Ravenclaw Slytherin Gryffindor Hufflepuff Ravenclaw  \
0          G0         H0        R0        S0        NaN        NaN       NaN   
1          G1         H1        R1        S1        NaN        NaN       NaN   
2          G2         H2        R2        S2        NaN        NaN       NaN   
3          G3         H3        R3        S3        NaN        NaN       NaN   
4         NaN        NaN       NaN       NaN         G4         H4        R4   
5         NaN        NaN       NaN       NaN         G5         H5        R5   
6         NaN        NaN       NaN       NaN         G6         H6        R6   
7         NaN        NaN       NaN       NaN         G7         H7        R7   
8         NaN        NaN       NaN       NaN        NaN        NaN       NaN   
9         NaN        NaN       NaN       NaN        NaN        NaN       NaN   
10        NaN        NaN       NaN       NaN        NaN        NaN       NaN   
11        NaN        NaN       NaN       NaN        NaN        NaN       NaN   

   Slytherin Gryffindor Hufflepuff Ravenclaw Slytherin  
0        NaN        NaN        NaN       NaN       NaN  
1        NaN        NaN        NaN       NaN       NaN  
2        NaN        NaN        NaN       NaN       NaN  
3        NaN        NaN        NaN       NaN       NaN  
4         S4        NaN        NaN       NaN       NaN  
5         S5        NaN        NaN       NaN       NaN  
6         S6        NaN        NaN       NaN       NaN  
7         S7        NaN        NaN       NaN       NaN  
8        NaN         G8         H8        R8        S8  
9        NaN         G9         H9        R9        S9  
10       NaN        G10        H10       R10       S10  
11       NaN        G11        H11       R11       S11

In [112]:
df1 = pd.DataFrame({'Gryffindor': ['G0', 'G1', 'G2', 'G3'],
                        'Hufflepuff': ['H0', 'H1', 'H2', 'H3'],
                        'Ravenclaw': ['R0', 'R1', 'R2', 'R3'],
                        'Slytherin': ['S0', 'S1', 'S2', 'S3']})
df2 = pd.DataFrame({'Gryffindor': ['G4', 'G5', 'G6', 'G7'],
                        'Hufflepuff': ['H4', 'H5', 'H6', 'H7'],
                        'Ravenclaw': ['R4', 'R5', 'R6', 'R7'],
                        'Slytherin': ['S4', 'S5', 'S6', 'S7']})
df3 = pd.DataFrame({'Gryffindor': ['G8', 'G9', 'G10', 'G11'],
                        'Hufflepuff': ['H8', 'H9', 'H10', 'H11'],
                        'Ravenclaw': ['R8', 'R9', 'R10', 'R11'],
                        'Slytherin': ['S8', 'S9', 'S10', 'S11']})

In [113]:
# И этот - с пересекающимся индексом
pd.concat([df1,df2,df3], axis=1)

Gryffindor Hufflepuff Ravenclaw Slytherin Gryffindor Hufflepuff Ravenclaw  \
0         G0         H0        R0        S0         G4         H4        R4   
1         G1         H1        R1        S1         G5         H5        R5   
2         G2         H2        R2        S2         G6         H6        R6   
3         G3         H3        R3        S3         G7         H7        R7   

  Slytherin Gryffindor Hufflepuff Ravenclaw Slytherin  
0        S4         G8         H8        R8        S8  
1        S5         G9         H9        R9        S9  
2        S6        G10        H10       R10       S10  
3        S7        G11        H11       R11       S11

In [114]:
# Append так же подходит для простых случаев склейки таблиц, но только по 0 оси.
df1.append(df2).append(df3)

Gryffindor Hufflepuff Ravenclaw Slytherin
0         G0         H0        R0        S0
1         G1         H1        R1        S1
2         G2         H2        R2        S2
3         G3         H3        R3        S3
0         G4         H4        R4        S4
1         G5         H5        R5        S5
2         G6         H6        R6        S6
3         G7         H7        R7        S7
0         G8         H8        R8        S8
1         G9         H9        R9        S9
2        G10        H10       R10       S10
3        G11        H11       R11       S11

In [115]:
# Очень полезная опция удаления индекса на случай, если он пересекающийся. 
# Часто по пересекающимуся индексу проблематично осуществлять индексирование. 
# Так что лучше всегда удалять индекс.
df1.append(df2).append(df3).reset_index(drop=True)

Gryffindor Hufflepuff Ravenclaw Slytherin
0          G0         H0        R0        S0
1          G1         H1        R1        S1
2          G2         H2        R2        S2
3          G3         H3        R3        S3
4          G4         H4        R4        S4
5          G5         H5        R5        S5
6          G6         H6        R6        S6
7          G7         H7        R7        S7
8          G8         H8        R8        S8
9          G9         H9        R9        S9
10        G10        H10       R10       S10
11        G11        H11       R11       S11

## Merging

**merge** позволяет объединять таблицы, следуя той же логике, что и в SQL.

In [116]:
left = pd.DataFrame({'key': ['Astronomy', 'Apparition', 'Charms', 'Flying', 'Herbology'],
                     'Gryffindor': ['G0', 'G1', 'G2', 'G3', 'G4'],
                     'Slytherin': ['S0', 'S1', 'S2', 'S3', 'S4']})
   
right = pd.DataFrame({'key': ['Astronomy', 'Charms', 'Flying', 'Potions', 'Herbology'],
                      'Hufflepuff': ['H0', 'H1', 'H2', 'H3', 'H4'],
                      'Ravenclaw': ['R0', 'R1', 'R2', 'R3', 'R4']})    

In [117]:
left

Gryffindor Slytherin         key
0         G0        S0   Astronomy
1         G1        S1  Apparition
2         G2        S2      Charms
3         G3        S3      Flying
4         G4        S4   Herbology

In [118]:
right

Hufflepuff Ravenclaw        key
0         H0        R0  Astronomy
1         H1        R1     Charms
2         H2        R2     Flying
3         H3        R3    Potions
4         H4        R4  Herbology

In [119]:
pd.merge(left,right,how='inner',on='key')

Gryffindor Slytherin        key Hufflepuff Ravenclaw
0         G0        S0  Astronomy         H0        R0
1         G2        S2     Charms         H1        R1
2         G3        S3     Flying         H2        R2
3         G4        S4  Herbology         H4        R4

In [120]:
pd.merge(left, right, how='outer', on='key')

Gryffindor Slytherin         key Hufflepuff Ravenclaw
0         G0        S0   Astronomy         H0        R0
1         G1        S1  Apparition        NaN       NaN
2         G2        S2      Charms         H1        R1
3         G3        S3      Flying         H2        R2
4         G4        S4   Herbology         H4        R4
5        NaN       NaN     Potions         H3        R3

In [121]:
pd.merge(left, right, how='right', on='key')

Gryffindor Slytherin        key Hufflepuff Ravenclaw
0         G0        S0  Astronomy         H0        R0
1         G2        S2     Charms         H1        R1
2         G3        S3     Flying         H2        R2
3         G4        S4  Herbology         H4        R4
4        NaN       NaN    Potions         H3        R3

In [122]:
pd.merge(left, right, how='left', on='key')

Gryffindor Slytherin         key Hufflepuff Ravenclaw
0         G0        S0   Astronomy         H0        R0
1         G1        S1  Apparition        NaN       NaN
2         G2        S2      Charms         H1        R1
3         G3        S3      Flying         H2        R2
4         G4        S4   Herbology         H4        R4

Есть и другие способы объединения таблиц в разных специфических случаях. Так что не пренебрегайте гуглением, там есть ответы на почти все ваши вопросы. Если ответа на ваш вопрос не нашлось, скорее всего, вы немного не так спрашиваете.

# Pandas: Ecommerce Purchases

In [123]:
import pandas as pd

In [124]:
ecom = pd.read_csv('Ecommerce Purchases.csv')

**Посмотреть на первые строки таблицы**

In [125]:
ecom.head()

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   
4        Brown, Watson and Andrews  6011456623207998       10/25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

**Сколько колонок и строк в таблице, какие типы имеют данные и насколько они заполнены?**

In [126]:
ecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
Address             10000 non-null object
Lot                 10000 non-null object
AM or PM            10000 non-null object
Browser Info        10000 non-null object
Company             10000 non-null object
Credit Card         10000 non-null int64
CC Exp Date         10000 non-null object
CC Security Code    10000 non-null int64
CC Provider         10000 non-null object
Email               10000 non-null object
Job                 10000 non-null object
IP Address          10000 non-null object
Language            10000 non-null object
Purchase Price      10000 non-null float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


##  Блиц!

**Какова средняя цена покупки?**

**Каковы максимальная и минимаьная цена покупки?**

**Сколько человек выбрали 'en' своим языком на сайте?**

**Сколько человек имеют работу юристом?**


**Сколько человек совершает покупки утром и сколько вечером?**

**Какие 5 самые популярные профессии?**

**Какова цена транзакции для лота "90 WT"?**

**Какой почтовый адрес у человека с номером карты: 4926535242672853**

**Сколько человек имеют American Express в качестве их Credit Card Provider и сделали покупку более $95 ?**

**Сколько человек имеют кредитную карточку, срок которой оканчивается в 2025 году?**

**Какие 5 самых популрных почтовых провайдеров? (e.g. gmail.com, yahoo.com, etc...)**