## Что делают - https://paperswithcode.com/sota
Градиентный спуск - https://hackernoon.com/life-is-gradient-descent-880c60ac1be8

In [1]:
import tensorflow as tf

/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.reset_default_graph()

In [3]:
def print_run(x):
    with tf.Session() as sess:
        print(sess.run(x))

In [4]:
a = tf.constant(1,dtype=tf.float16)

In [18]:
print(a)

Tensor("Const:0", shape=(), dtype=float16)


In [19]:
with tf.Session() as sess:
    print(sess.run(a))

1.0


In [5]:
print_run(a)

1.0


In [6]:
hello_world = tf.constant('Hello World')

In [7]:
print_run(hello_world)

b'Hello World'


In [8]:
k = tf.constant(8.0, name="k")
l = tf.constant(12.0, name="l")

In [9]:
m = k+l

In [22]:
n = tf.add(k,l,name='add_n')

In [17]:
m==n

False

In [16]:
with tf.Session() as sess:
    print(sess.run(m)==sess.run(n))

True


In [23]:
graph = tf.get_default_graph()

In [24]:
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'k' type=Const>,
 <tf.Operation 'l' type=Const>,
 <tf.Operation 'add' type=Add>,
 <tf.Operation 'add_1' type=Add>,
 <tf.Operation 'add_n' type=Add>]

In [50]:
tf.reset_default_graph()

In [55]:
a = tf.placeholder(dtype=tf.float16,shape=[1])

In [69]:
c=a+1

In [58]:
A = tf.Variable(0,dtype=tf.float16)
C= A+1

In [60]:
with tf.Session() as sess:
    sess.run(C)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[node Variable/read (defined at <ipython-input-58-1dcb31ee2cf0>:1)  = Identity[T=DT_HALF, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

Caused by op 'Variable/read', defined at:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 112, in start
    self.asyncio_loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1431, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-58-1dcb31ee2cf0>", line 1, in <module>
    A = tf.Variable(0,dtype=tf.float16)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 183, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 146, in _variable_v1_call
    aggregation=aggregation)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 125, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2444, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 187, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1329, in __init__
    constraint=constraint)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1491, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 81, in identity
    return gen_array_ops.identity(input, name=name)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3454, in identity
    "Identity", input=input, name=name)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Variable
	 [[node Variable/read (defined at <ipython-input-58-1dcb31ee2cf0>:1)  = Identity[T=DT_HALF, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]


In [65]:
with tf.Session() as sess:
    sess.run(tf.variables_initializer([A]))
    print(sess.run(C))

1.0


In [80]:
with tf.Session() as sess:
    print(sess.run(c,feed_dict={a:[2]}))

[3.]


In [82]:
help(tf.matmul)

Help on function matmul in module tensorflow.python.ops.math_ops:

matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)
    Multiplies matrix `a` by matrix `b`, producing `a` * `b`.
    
    The inputs must, following any transpositions, be tensors of rank >= 2
    where the inner 2 dimensions specify valid matrix multiplication arguments,
    and any further outer dimensions match.
    
    Both matrices must be of the same type. The supported types are:
    `float16`, `float32`, `float64`, `int32`, `complex64`, `complex128`.
    
    Either matrix can be transposed or adjointed (conjugated and transposed) on
    the fly by setting one of the corresponding flag to `True`. These are `False`
    by default.
    
    If one or both of the matrices contain a lot of zeros, a more efficient
    multiplication algorithm can be used by setting the corresponding
    `a_is_sparse` or `b_is_sparse` flag to `True`. T

______

In [84]:
from tensorflow.python.framework import ops

In [87]:
tf.reset_default_graph()

In [88]:
weights = tf.Variable(tf.random_normal([2, 5], stddev=0.1),
                      name="W")
biases = tf.Variable(tf.zeros([5]), name="B")
custom_variable = tf.Variable(tf.zeros([5]), name="custom")

all_variables_list = ops.get_collection(ops.GraphKeys.GLOBAL_VARIABLES)

In [89]:
all_variables_list

[<tf.Variable 'W:0' shape=(2, 5) dtype=float32_ref>,
 <tf.Variable 'B:0' shape=(5,) dtype=float32_ref>,
 <tf.Variable 'custom:0' shape=(5,) dtype=float32_ref>]

In [92]:
init = tf.variables_initializer(var_list=all_variables_list )
init2 = tf.global_variables_initializer()

In [102]:
with tf.Session() as sess:
#     sess.run(init)
    sess.run(init2)
    print(sess.run(weights))

[[-0.05802175  0.11733109  0.00792276 -0.07500669 -0.1173496 ]
 [-0.08374085  0.06587733 -0.08651923  0.11216255 -0.15374163]]


In [103]:
tf.reset_default_graph()

In [109]:
a = tf.range(10,20)

In [110]:
print_run(a)

[10 11 12 13 14 15 16 17 18 19]


In [111]:
b = a[-3:]

In [112]:
print_run(b)

[17 18 19]


In [114]:
x = tf.reduce_max(a)

In [115]:
print_run(x)

19


In [116]:
x = tf.reduce_mean(a)

In [117]:
print_run(x)

14


In [120]:
n=tf.random_uniform(shape=(2,2))

In [123]:
print_run(n)

[[0.9122312  0.462803  ]
 [0.53669894 0.01146317]]


In [124]:
print_run(n)

[[0.6635463  0.5300691 ]
 [0.18489027 0.69973886]]


In [137]:
n1=tf.random_uniform(shape=(2,2),seed=2121)
print_run(n1)

[[0.32178426 0.18638146]
 [0.21707845 0.6910995 ]]


In [146]:
nc=tf.eye(10)

In [147]:
print_run(nc)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [153]:
print_run(nc)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [154]:
print_run(tf.split(nc,2))

[array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32), array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)]
